### PR TITLE
Support custom join function

### PR DESCRIPTION
**Pull request by david-zacharias**
This is an enhancement for the issue discussed in #5. It gives developers the possibility to define a custom _join function_ which is used for calling the native logger method given by loglevel.

**Usage like:**

``` JS
loglevelMessagePrefix(log, {
  joinFunction: function(fn_method_raw, prefix, message) {
    fn_method_raw(prefix + ' - ' + message);
   }
});
```

My PR adds support for this and uses current implementation as _default function_. PR also includes a test for this new behavior.

Hope you like this change. :two_men_holding_hands: 

P.S. While working on the code I wondered about the indentation (e.g. often sub level code is on one level with parent code) is that done on purpose? Also some code looks surplus, like `prefix = prefix.substr(0, prefix.length);`.

### CODE REVIEW

**Comment by ghost** [comment]
Hello,

Thank you for your recommendations. Here are my answers:

> This is an enhancement for the issue discussed in #5. It gives developers the possibility to define a custom join function which is used for calling the native logger method given by loglevel.

loglevel-message-prefix can be configured using an optional second argument of the function. I'll add [a new option](https://github.com/NatLibFi/loglevel-message-prefix/issues/7) which allows defining the prefix and the message separator string.

> Also some code looks surplus, like prefix = prefix.substr(0, prefix.length);. 

That assignment is indeed surplus and was leftover from a previous implementation. Will be [fixed](https://github.com/NatLibFi/loglevel-message-prefix/issues/8).

> I wondered about the indentation (e.g. often sub level code is on one level with parent code) is that done on purpose?

Can you give an example line in the code where this occurs.

**Comment by david-zacharias** [comment]
Hi again and sorry for overseeing your answers at first.

Regarding configuration: As originally written in #5 I would lik to comma-separate prefix and message as this leads to nice logging in browser environments using `console.log`. If possible with defining the new option I am very happy with it.

Regarding indentation: Do you use tab-size 8? That would explain why I (using tab-size 4 by default) have a cluttered indentation, due to mixed spaces and tabs. Personally I try not to mix tabs and spaces for indentation and use _no-mixed-spaces-and-tabs_ from [eslint](http://eslint.org/docs/2.0.0/rules/no-mixed-spaces-and-tabs.html) to ensure this. Maybe you want to add a [.editorconfig](http://editorconfig.org/) as well, so developers with other IDE settings see the code with your settings.

**Comment by ghost** [comment]
My editor's indentation may very well be non-standard. This is something I've been planning to fix for some time. I'll [look in to it](https://github.com/NatLibFi/loglevel-message-prefix/issues/9).

**Comment by ghost** [comment]
The prefix part of the message can now be formatted using `prefixFormat` option (Implemented in ac6afa2393f5c5249351f8443c68692ea198851c).

**Pull request closed without merging**
